InseeFr/Bauhaus

- src/js/components/operations/shared/relations/index.js
- src/js/utils/msd/index.js
- src/js/utils/msd/index.spec.js
And test the IFTTT/Github/Trello hooks :D
> PR  solve the issue with flags

- app/src/js/applications/auth/open-id-connect-auth/login-container.js
🛑🛑🛑🛑🛑🛑🛑 ATTENTION 🛑🛑🛑🛑🛑🛑🛑 
This PR modify the Login component used only on production. 
We have to take care of the rollback if needed.
> Rewrite login component

- .github/workflows/ci.yml
- README.md
- docs/book.json
- docs/en/getting-started.md
- docs/fr/getting-started.md
- scripts/gitbook.sh
Replaced all references to master except :
- xxx/node-modules/xxx
- packages/xxx/dist/index.js.map
@EmmanuelDemey : does my list of evolutions seems to be ok ?
> replace reference to branch master with branch main

- app/src/js/applications/classifications/visualization/items/home-container.js
- app/src/js/applications/operations/msd/pages/sims-creation/index.js
- app/src/js/remote-api/operations/series.js
> Revert "Get Series with Sims "

- app/src/js/applications/classifications/visualization/items/home-container.js
- app/src/js/applications/operations/msd/pages/sims-creation/index.js
- app/src/js/remote-api/operations/series.js
> Revert "Revert "Get Series with Sims ""

- packages/operations/src/sims/sims-geography-picker.js
Wait for the territory to be loaded to show the geography select
> Show geography select only when territory is loaded

- packages/operations/src/sims/sims-geography-picker.js
> Revert "correct address of label and typeTerritory in select options"

- packages/operations/src/sims/sims-geography-picker.js
> Revert "Show geography select only when territory is loaded"

- app/src/js/applications/operations/document/edition/edition.js
@EmmanuelDemey 
No metadata of the Document were updated when its file was changed.
> Dev operations documents save bug

- packages/codelists/src/apis/codelists-api.js
- packages/codelists/src/components/code-detail/edit.js
- packages/codelists/src/components/codelist-detail/edit.js
- packages/codelists/src/components/codelist-detail/view-container.js
- packages/codelists/src/components/codelist-detail/view.js
- packages/codelists/src/components/codelist-partial-detail/view-container.js
- packages/codelists/src/components/codelist-partial-detail/view.js
- packages/codelists/src/i18n/dictionary.js
- packages/codelists/src/utils/index.js
- create new code as a sibling of the current one
- delete codelists
- add lastCodeUriSegment
- add error : a codeList should contain at least 1 Code
> Dev partial codelists

- app/package.json
- package.json
> fix(version) increment to 3.4.0

- app/src/js/applications/collections/visualization/controls.js
- app/src/js/applications/operations/msd/outline/index.spec.js
> feat: fix warning inside unit test #415

- .github/workflows/ci.yml
> feat: remove Node 14 from Github Action #417

- app/src/js/applications/collections/visualization/controls.js
> fix: solve issue when exporting a collection

- .github/workflows/ci.yml
- app/src/js/applications/collections/edition-creation/general.js
- app/src/js/applications/concepts/edition-creation/general.js
- app/src/js/applications/help/content-concepts.js
- app/src/js/applications/operations/indicators/edition/edition.js
- app/src/js/applications/shared/input-rmes/index.js
- app/src/js/applications/shared/input-rmes/input-rmes.spec.js
- packages/utilities/src/components/required-icon/index.js
- packages/utilities/src/components/required-icon/requiredIcon.scss
- packages/utilities/src/index.js
> feat: add required icon

- app/src/js/applications/classifications/item/edition/index.js
> fix: solve sonar issue

- app/src/js/applications/operations/document/utils.js
- app/src/js/applications/operations/document/utils.spec.js
> fix: solve issue with document page

- app/src/js/applications/operations/document/utils.js
- app/src/js/applications/operations/document/utils.spec.js
> fix: solve issue with documents

- app/src/index.js
- package.json
- yarn.lock
> fix: #451 add sentry

- app/src/js/applications/concepts/visualization/controls.js
- app/src/js/applications/concepts/visualization/home-container.js
- app/src/js/applications/concepts/visualization/loading.js
> feat: remove confirmation modal when exporting a concept

- app/src/js/applications/concepts/advanced-search/controls.js
- app/src/js/applications/concepts/advanced-search/controls.spec.js
- app/src/js/applications/concepts/advanced-search/home-container.js
- app/src/js/applications/concepts/advanced-search/home.js
> feat: be able to download a list of concepts from the Advanced Search page

- package.json
- yarn.lock
> feat: remove node fetch

- app/src/js/applications/operations/document/edition/edition.js
- app/src/js/applications/operations/document/edition/edition.spec.js
- app/src/js/i18n/dictionary/app.js
- package.json
- yarn.lock
> Résoudre le problème de création d'un document

- app/.env
- app/src/js/applications/classifications/item/general.js
- app/src/js/utils/auth/no-auth/utils.js
- packages/structures/src/components/component-detail/edit.js
- packages/structures/src/components/component-detail/view-container.js
- packages/structures/src/components/component-detail/view-container.spec.js
- packages/structures/src/components/component-detail/view.js
- packages/structures/src/i18n/dictionary.js
* feat: make contributor editable for a structure #362
* feat: add altLabel for structure component #366
* fix: solve eslint issues
> Add Structure Component altLabel

- packages/codelists/src/i18n/dictionary.js
- packages/codelists/src/utils/index.js
- packages/codelists/src/utils/index.spec.js
* feat: make contributor editable for a structure #362
* Particla Code List identifier should contain only a-zA-Z0-9_ #382
> Feat/validation codelist (#404)

- app/package.json
> Revert "feat: remove zip"

- src/packages/auth/open-id-connect-auth/use-oidc.tsx
> fix (cannot login)

- src/packages/auth/components/auth.ts
- src/packages/auth/hoc.tsx
- src/packages/modules-operations/families/index.tsx
- src/packages/modules-operations/families/visualization/menu.spec.tsx
- src/packages/modules-operations/families/visualization/menu.tsx
- src/packages/sdk/users-api.ts
- src/packages/tests-utils/render.tsx
> Revert "feat: implement new security layer for families"
